--replace this with your query
SELECT
	CAND_PTY_AFFILIATION,
	count(*) as NUM_SENATE_CAND

FROM 
	CANDIDATE
WHERE
	CAND_OFFICE = "S"
	AND CAND_STATUS IN ('C','N')
	AND CAND_ELECTION_YR = 2016
	AND CAND_PTY_AFFILIATION NOT IN ('IND','DEM','REP')
GROUP BY
	CAND_PTY_AFFILIATION
ORDER BY
	NUM_SENATE_CAND desc
LIMIT
	1;

