--replace this with your query
SELECT 
	CANDIDATE.CAND_NAME,
	CAND_PTY_AFFILIATION,
	TTL_INDIV_CONTRIB,
	TTL_RECEIPTS,
	TTL_INDIV_CONTRIB/TTL_RECEIPTS as ttl_indiv_ratio

FROM
	CANDIDATE,
	CAND_SUMMARY

WHERE
	CANDIDATE.CAND_ID = CAND_SUMMARY.CAND_ID

AND CAND_OFFICE = 'H'
AND CAND_STATUS IN ('C','N')
AND CAND_ELECTION_YR = 2016
AND TTL_RECEIPTS >= 100000

ORDER BY
	ttl_indiv_ratio ASC

LIMIT 
	10;