--replace this with your query
SELECT 
	CAND_PTY_AFFILIATION,
	SUM(TTL_INDIV_CONTRIB),
	SUM(TTL_RECEIPTS),
	SUM(TTL_INDIV_CONTRIB)/SUM(TTL_RECEIPTS) as TTL_INDIV_RATIO
FROM
	CANDIDATE,
	CAND_SUMMARY
WHERE
	CANDIDATE.CAND_ID = CAND_SUMMARY.CAND_ID

AND CAND_OFFICE = 'S'
AND CAND_STATUS IN ('C','N')
AND CAND_ELECTION_YR = 2016

GROUP BY
	CAND_PTY_AFFILIATION

ORDER BY
	TTL_INDIV_RATIO DESC

LIMIT 
	10;



